django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("", include("tickets.urls")),
    path("", include("adminlte2_pdq.urls")),
]

tickets/urls.py
from django.urls import path

from .views import (
    OpenTicketListView,
    ClosedTicketListView,
    TicketCreateView,
    TicketUpdateView,
    TicketDeleteView,
)

urlpatterns = [
    path("", OpenTicketListView.as_view(), name="open_ticket_list"),
    path("tickets/closed/", ClosedTicketListView.as_view(), name="closed_ticket_list"),
    path("tickets/create/", TicketCreateView.as_view(), name="ticket_create"),
    path("tickets/<int:pk>/update/", TicketUpdateView.as_view(), name="ticket_update"),
    path("tickets/<int:pk>/delete/", TicketDeleteView.as_view(), name="ticket_delete"),
]

tickets/models.py
from django.db import models

# Choices for Priority
PRIORITY_CHOICES = (
    (1, "High"),
    (2, "Medium"),
    (3, "Low"),
)


class Ticket(models.Model):
    """Represents a ticket for project."""

    assigned_to = models.ForeignKey(
        "auth.User",
        on_delete=models.CASCADE,
        related_name="tickets",
        blank=True,
        null=True,
    )

    name = models.CharField(max_length=250)
    description = models.TextField()
    priority = models.IntegerField(choices=PRIORITY_CHOICES)
    complete_by = models.DateField(blank=True, null=True)
    completed = models.BooleanField(default=False)

    def __str__(self):
        """str conversion"""
        return self.name

tickets/views.py
from django.contrib import messages
from django.views.generic import ListView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse

from .models import Ticket


class OpenTicketListView(TemplateView):
    """Show lists of open tickets by priority"""

    template_name = "ticket_list_open.html"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.extra_context = {
            "open_high_tickets": Ticket.objects.filter(priority=1, completed=False),
            "open_medium_tickets": Ticket.objects.filter(priority=2, completed=False),
            "open_low_tickets": Ticket.objects.filter(priority=3, completed=False),
        }


class ClosedTicketListView(ListView):
    """Show list of closed tickets"""

    model = Ticket
    template_name = "ticket_list_closed.html"

    def get_queryset(self):
        return Ticket.objects.filter(completed=True)


class TicketCreateView(CreateView):
    """Create a new ticket"""

    model = Ticket
    template_name = "ticket_create.html"
    fields = "__all__"

    def get_success_url(self):
        """Where to send user on success"""
        messages.success(self.request, "Ticket Created Successfully")
        return reverse("open_ticket_list")


class TicketUpdateView(UpdateView):
    """Update a ticket"""

    model = Ticket
    template_name = "ticket_update.html"
    fields = "__all__"

    def get_success_url(self):
        """Where to send user on success"""
        messages.success(self.request, "Ticket Updated Successfully")
        return reverse("open_ticket_list")


class TicketDeleteView(DeleteView):
    """Delete a ticket"""

    model = Ticket
    template_name = "ticket_delete.html"

    def get_success_url(self):
        """Where to send user on success"""
        messages.success(self.request, "Ticket Deleted Successfully")
        return reverse("open_ticket_list")

templates/_ticket_box.html
<div class="box box-solid box-{{ color }}">
  <div class="box-header with-border">
    <h3 class="box-title">{{ priority }} Tickets</h3>
  </div>
  <div class="box-body">
    {% if tickets.exists %}
      <table class="table">
        <tr>
          <th>Name</th>
          <th>Assigned To</th>
          <th>Complete By</th>
          <th class="text-right">Actions</th>
        </tr>
        {% for ticket in tickets.all %}
          <tr>
            <td>{{ ticket.name }}</td>
            <td>{{ ticket.assigned_to.username }}</td>
            <td>{{ ticket.complete_by }}</td>
            <td class="text-right">
              <a href="{% url "ticket_update" ticket.pk %}" class="btn btn-success">
                <i class="fa fa-pencil"></i> Update
              </a>
              <a href="{% url "ticket_delete" ticket.pk %}" class="btn btn-danger">
                <i class="fa fa-times"></i> Delete
              </a>
            </td>
          </tr>
        {% endfor %}
      </table>
    {% else %}
      <h3>No Tickets For This Priority Level</h3>
    {% endif %}
  </div>
</div>

templates/_ticket_breadcrumb.html
<ol class="breadcrumb">
  <li>
    <i class="fa fa-dashboard"></i>
    <a href="{% url 'open_ticket_list' %}">Home</a>
  </li>
  {% if icon and action %}
    <li class="active"><i class="fa fa-{{ icon }}"></i> {{ action }} Ticket</li>
  {% endif %}
</ol>

templates/_ticket_form.html
{% load adminlte_tags %}
<div class="box box-solid box-{{ color }}">
  <div class="box-header with-border">
    <h3 class="box-title">{{ action }} Ticket</h3>
  </div>
  <div class="box-body">
    <form method="post">
      {% csrf_token %}
      {% if action == "Delete" %}
        <p>
          <h4>Are you sure you want to delete this ticket?</h4>
          - {{ ticket.name }}
        </p>
      {% else %}
        {% render_form form %}
      {% endif %}
      <button type="submit" class="btn btn-{{ color }}">
        <i class=""></i> {{ action }}
      </button>
    </form>
  </div>
</div>

templates/ticket_create.html
{% extends "adminlte2/base.html" %}

{% block page_name %}
Create Ticket
{% endblock page_name %}

{% block breadcrumbs %}
  {% include "_ticket_breadcrumb.html" with icon="plus" action="Create" %}
{% endblock breadcrumbs %}

{% block content %}
  {% include "_ticket_form.html" with color="primary" action="Create" %}
{% endblock content %}

templates/ticket_delete.html
{% extends "adminlte2/base.html" %}

{% block page_name %}
Delete Ticket
{% endblock page_name %}

{% block breadcrumbs %}
  {% include "_ticket_breadcrumb.html" with icon="times" action="Delete" %}
{% endblock breadcrumbs %}

{% block content %}
{% include "_ticket_form.html" with color="danger" action="Delete" %}
{% endblock content %}

templates/ticket_list_closed.html
{% extends "adminlte2/base.html" %}

{% block page_name %}
Closed Tickets
{% endblock page_name %}

{% block breadcrumbs %}
  {% include "_ticket_breadcrumb.html" with icon="ticket" action="Closed" %}
{% endblock breadcrumbs %}

{% block content %}
  {% include "_ticket_box.html" with tickets=ticket_list color="purple" priority="Closed" %}
{% endblock content %}

templates/ticket_list_open.html
{% extends "adminlte2/base.html" %}

{% block page_name %}
Open Tickets
{% endblock page_name %}

{% block breadcrumbs %}
  {% include "_ticket_breadcrumb.html" with icon="ticket" action="Open" %}
{% endblock breadcrumbs %}

{% block content %}

  <a href="{% url "ticket_create" %}" class="btn btn-primary pull-right">
    <i class="fa fa-plus"></i> New Ticket
  </a>

  <br><br>

  {% include "_ticket_box.html" with tickets=open_high_tickets color="danger" priority="High Priority" %}
  {% include "_ticket_box.html" with tickets=open_medium_tickets color="warning" priority="Medium Priority" %}
  {% include "_ticket_box.html" with tickets=open_low_tickets color="info" priority="Low Priority" %}

{% endblock content %}

templates/ticket_update.html
{% extends "adminlte2/base.html" %}

{% block page_name %}
Update Ticket
{% endblock page_name %}

{% block breadcrumbs %}
  {% include "_ticket_breadcrumb.html" with icon="pencil" action="Update" %}
{% endblock breadcrumbs %}

{% block content %}
  {% include "_ticket_form.html" with color="success" action="Update" %}
{% endblock content %}